### ISSUE TITLE
Uncaught MongoError: explain must be one of queryPlanner,queryPlannerExtended,executionStats,allPlansExecution or a boolean   

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-storage-mongodb#58]
```js

  78 passing (13m)
  2 failing

  1) Operation Storage API
       exists API
         properly indexed with operationHash param:
     Uncaught MongoError: explain must be one of queryPlanner,queryPlannerExtended,executionStats,allPlansExecution or a boolean                                                                                                  
      at Function.fromOptions (node_modules/mongodb/lib/explain.js:51:11)                                        
      at Object.query (node_modules/mongodb/lib/core/wireprotocol/query.js:40:27)                                
      at Connection.query (node_modules/mongodb/lib/cmap/connection.js:175:8)                                    
      at /home/liminal18/Programs/nodeJS/digital_bazaar/bedrock-ledger-storage-mongodb/test/node_modules/mongodb/lib/core/sdam/server.js:309:12                                                                                   
      at Object.callback (node_modules/mongodb/lib/cmap/connection_pool.js:345:7)                                
      at processWaitQueue (node_modules/mongodb/lib/cmap/connection_pool.js:468:23)                              
      at /home/liminal18/Programs/nodeJS/digital_bazaar/bedrock-ledger-storage-mongodb/test/node_modules/mongodb/lib/cmap/connection_pool.js:236:28                                                                               
      at processTicksAndRejections (internal/process/task_queues.js:75:11)                                       
                                                                                                                 
  2) Operation Storage API
       exists API
         properly indexed with operationHash and eventHash params:
     Uncaught MongoError: explain must be one of queryPlanner,queryPlannerExtended,executionStats,allPlansExecution or a boolean                                                                                                  
      at Function.fromOptions (node_modules/mongodb/lib/explain.js:51:11)                                        
      at Object.query (node_modules/mongodb/lib/core/wireprotocol/query.js:40:27)                                
      at Connection.query (node_modules/mongodb/lib/cmap/connection.js:175:8)                                    
      at /home/liminal18/Programs/nodeJS/digital_bazaar/bedrock-ledger-storage-mongodb/test/node_modules/mongodb/lib/core/sdam/server.js:309:12                                                                                   
      at Object.callback (node_modules/mongodb/lib/cmap/connection_pool.js:345:7)                                
      at processWaitQueue (node_modules/mongodb/lib/cmap/connection_pool.js:468:23)                              
      at /home/liminal18/Programs/nodeJS/digital_bazaar/bedrock-ledger-storage-mongodb/test/node_modules/mongodb/lib/cmap/connection_pool.js:236:28                                                                               
      at processTicksAndRejections (internal/process/task_queues.js:75:11)                                       
                                                                                                                 


Tests failed.
2021-04-06T23:07:24.564Z - critical: [bedrock/master] worker "20813" exited with code "1" and signal "null".
npm ERR! Test failed.  See above for more details.
```

**Comment by aljones15** [comment]
Other uses of explain in our code base:

https://github.com/search?q=org%3Adigitalbazaar+in%3Afile+explain&type=code

**Comment by aljones15** [comment]
closing as other repos were checked for the bug and are fine and fix is in.
